---
target: mpc85xx/p1010
brand_nice: TP-Link
model_nice: WDR4900
version_nice: v1

openwrt_version: 24.10-SNAPSHOT

dsa_ports:
  - wan
  - lan1
  - lan2
  - lan3
  - lan4

wireless_devices:
  - name: 11a_standard
    band: 5g
    htmode_prefix: HT
    path: ffe09000.pcie/pci9000:00/9000:00:00.0/9000:01:00.0
    ifname_hint: wlan5
  - name: 11g_standard
    band: 2g
    htmode_prefix: HT
    path: ffe0a000.pcie/pcia000:02/a000:02:00.0/a000:03:00.0
    ifname_hint: wlan2
