---
target: ramips/mt7621
brand_nice: Ubiquiti
model_nice: EdgeRouter X SFP

openwrt_version: 23.05-SNAPSHOT

dsa_ports:
  - eth0
  - eth1
  - eth2
  - eth3
  - eth4
  - eth5

poe_ports:
  - name: PoE Power Port0
    gpio_pin: 400
    value: 0
  - name: PoE Power Port1
    gpio_pin: 401
    value: 0
  - name: PoE Power Port2
    gpio_pin: 402
    value: 0
  - name: PoE Power Port3
    gpio_pin: 403
    value: 0
  - name: PoE Power Port4
    gpio_pin: 404
    value: 0
