---
target: ath79/generic
os: openwrt
brand_nice: Ubiquiti
model_nice: Powerbeam M5
version_nice: XW

int_port: eth0

low_mem: true

wireless_devices:
  - name: 11a_standard
    band: 5g
    htmode_prefix: HT
    path: platform/ahb/18100000.wmac
    ifname_hint: wlan5
    antenna_gain: 12
