---
imagebuilder: "https://downloads.openwrt.org/releases/21.02-SNAPSHOT/targets/ramips/mt76x8/openwrt-imagebuilder-21.02-SNAPSHOT-ramips-mt76x8.Linux-x86_64.tar.xz"
feed_version: "1.2.0-snapshot"
imagebuilder_disable_signature_check: true

switch_ports: 7
switch_int_port: 6
switch_ignore_ports: [5]

int_port: eth0

wireless_devices:
  - name: 11a_standard
    hwmode: 11a
    path: pci0000:00/0000:00:00.0/0000:01:00.0
    ifname_hint: wlan5
  - name: 11g_standard
    hwmode: 11g
    path: platform/10300000.wmac
    ifname_hint: wlan2

leds:
  - name: lan
    sysfs: green:lan
    trigger: switch0
    port_mask: 0x1e
  - name: wan
    sysfs: green:wan
    trigger: switch0
    port_mask: 0x01
  - name: wlan2g
    sysfs: green:wlan2g
    trigger: phy0tpt
  - name: wlan5g
    sysfs: green:wlan5g
    trigger: phy1tpt

