---
target: ath79/generic
brand_nice: Siemens
model_nice: WS-AP3610

openwrt_version: 24.10-SNAPSHOT

int_port: eth0

wireless_devices:
  - name: 11a_standard
    band: 5g
    htmode_prefix: HT
    path: pci0000:00/0000:00:11.0
    ifname_hint: wlan5
  - name: 11g_standard
    band: 2g
    htmode_prefix: HT
    path: pci0000:00/0000:00:12.0
    ifname_hint: wlan2
