---
override_target: "ubnt_nanostation-m"
target: ath79/tiny
openwrt_version: 22.03-SNAPSHOT

int_port: eth1

low_mem: true

wireless_devices:
  - name: 11g_standard
    band: 2g
    htmode_prefix: HT
    path: pci0000:00/0000:00:00.0
    ifname_hint: wlan2
    antenna_gain: 8

poe_ports:
  - name: PoE Passthrough
    gpio_pin: 8
    value: 0
