---
target: mediatek/mt7622
brand_nice: Sinovoip
model_nice: Banana Pi R64
openwrt_version: 25.12-SNAPSHOT

dsa_ports:
  - wan
  - lan1
  - lan2
  - lan3
  - lan4

wireless_devices:
  - name: 11g_standard
    band: 2g
    htmode_prefix: HT
    path: platform/18000000.wmac
    ifname_hint: wlan2
