---
target: ath79/generic
brand_nice: TP-Link
model_nice: EAP225
version_nice: v1

openwrt_version: 24.10-SNAPSHOT

int_port: eth0

model__packages__to_merge:
  - "-ath10k-firmware-qca9888-ct ath10k-firmware-qca9888-ct-full-htt" # select candelatech suggested firmware variant

wireless_devices:
  - name: 11a_standard
    band: 5g
    htmode_prefix: VHT
    path: pci0000:00/0000:00:00.0
    ifname_hint: wlan5
  - name: 11g_standard
    band: 2g
    htmode_prefix: HT
    path: platform/ahb/18100000.wmac
    ifname_hint: wlan2

ath10k_ct_fwcfg:
  - id: pci-0000:00:00.0
    config: |
      vdevs = 4
      peers = 96
      active_peers = 96
      stations = 96
