---
target: ath79/generic
os: openwrt
brand_nice: TP-Link
model_nice: WDR3500
version_nice: v1

switch_ports: 5
switch_int_port: 0

int_port: eth0

wireless_devices:
  - name: 11a_standard
    band: 5g
    htmode_prefix: HT
    path: pci0000:00/0000:00:00.0
    ifname_hint: wlan5
  - name: 11g_standard
    band: 2g
    htmode_prefix: HT
    path: platform/ar934x_wmac
    ifname_hint: wlan2
