---
target: ath79/generic
os: openwrt
brand_nice: TP-Link
model_nice: CPE510
version_nice: v1

# PoE port is eth1, 2nd port is eth0
# override port in host_vars if required
int_port: eth1

wireless_devices:
  - name: 11a_standard
    band: 5g
    htmode_prefix: HT
    path: platform/ahb/18100000.wmac
    ifname_hint: wlan5
