---
target: ath79/generic
brand_nice: TP-Link
model_nice: TL-WR842N
version_nice: v3

openwrt_version: 23.05-SNAPSHOT

# eth0 is the switch, eth1 is WAN; just use WAN
int_port: eth1

wireless_devices:
  - name: 11g_standard
    band: 2g
    htmode_prefix: HT
    path: platform/ahb/18100000.wmac
    ifname_hint: wlan2
