---
target: ramips/mt7621
os: openwrt
brand_nice: TOTOLINK
model_nice: A7000R

dsa_ports:
  - wan
  - lan1
  - lan2
  - lan3
  - lan4

wireless_devices:
  - name: 11g_standard
    band: 2g
    htmode_prefix: HT
    path: 1e140000.pcie/pci0000:00/0000:00:00.0/0000:01:00.0
    ifname_hint: wlan2
  - name: 11a_standard
    band: 5g
    htmode_prefix: VHT
    path: 1e140000.pcie/pci0000:00/0000:00:01.0/0000:02:00.0
    ifname_hint: wlan5
