---
override_target: "ubnt_nanostation-loco-m"
target: ath79/tiny
brand_nice: Ubiquiti
model_nice: Nanostation Loco M5
version_nice: XM

openwrt_version: 23.05-SNAPSHOT

int_port: eth0

low_mem: true

wireless_devices:
  - name: 11a_standard
    band: 5g
    htmode_prefix: HT
    path: pci0000:00/0000:00:00.0
    ifname_hint: wlan5
