---
imagebuilder: "https://downloads.openwrt.org/releases/21.02-SNAPSHOT/targets/ath79/generic/openwrt-imagebuilder-21.02-SNAPSHOT-ath79-generic.Linux-x86_64.tar.xz"
feed_version: "1.2.0-snapshot"
override_target: "ubnt_nanostation-m"

int_port: eth1

wireless_devices:
  - name: 11g_standard
    hwmode: 11g
    path: pci0000:00/0000:00:00.0
    ifname_hint: wlan2
