---
ipv6_prefix: "2001:bf7:830:9800::/56"


# Zwingli got 10.31.115.0/24

networks:
  - vid: 42
    role: mgmt
    prefix: 10.31.115.0/27
    gateway: 1
    dns: 1
    ipv6_subprefix: 1
    assignments:
      zwingli-core: 1
      zwingli-switch: 2
# af60-lr
      zwingli-sama: 3
#      zwingli-rhnk: 4
      zwingli-agym: 5
      zwingli-vaterhaus: 6
# legacy link to emma
      zwingli-emma: 7
# local aps 2ghz
      zwingli-nord-nf-2ghz: 10
      zwingli-ost-nf-2ghz: 11
#      zwingli-sued-nf-2ghz: 12
      zwingli-west-nf-2ghz: 13
# local aps 5ghz
      zwingli-nord-nf-5ghz: 14
      zwingli-ost-nf-5ghz: 15
      zwingli-nno-nf-5ghz: 16
      zwingli-west-nf-5ghz: 17
# dome inside church
      zwingli-dome-1: 18
      zwingli-dome-2: 19
# 5ghz sectors
      zwingli-nord-5ghz: 20
      zwingli-ost-5ghz: 21
      zwingli-sued-5ghz: 22
      zwingli-west-5ghz: 23

  - vid: 40
    role: dhcp
    prefix: 10.31.115.128/25
    ipv6_subprefix: 0
    inbound_filtering: true
    enforce_client_isolation: true
    assignments:
      zwingli-core: 1


# 10.31.115.32/27 Mesh Prefix (32)
  - vid: 10
    role: mesh
    name: mesh_nord
    prefix: 10.31.115.32/32
    ipv6_subprefix: -1
  - vid: 11
    role: mesh
    name: mesh_ost
    prefix: 10.31.115.33/32
    ipv6_subprefix: -2
  - vid: 12
    role: mesh
    name: mesh_sued
    prefix: 10.31.115.34/32
    ipv6_subprefix: -3
  - vid: 13
    role: mesh
    name: mesh_west
    prefix: 10.31.115.35/32
    ipv6_subprefix: -4
  - vid: 14
    role: mesh
    name: mesh_sama
    prefix: 10.31.115.36/32
    ipv6_subprefix: -5
    mesh_metric: 128
    ptp: true
#  - vid: 15
#    role: mesh
#    name: mesh_rhnk
#    prefix: 10.31.115.37/32
#    ipv6_subprefix: -6
#    mesh_metric: 128
#    ptp: true
  - vid: 16
    role: mesh
    name: mesh_agym
    prefix: 10.31.115.38/32
    ipv6_subprefix: -7
    mesh_metric: 128
    ptp: true
  - vid: 17
    role: mesh
    name: mesh_vaterhaus
    prefix: 10.31.115.39/32
    ipv6_subprefix: -8
    mesh_metric: 128
    ptp: true
  - vid: 18
    role: mesh
    name: mesh_emma
    prefix: 10.31.115.40/32
    ipv6_subprefix: -9
    mesh_metric: 128
    mesh_metric_lqm:
      - default 0.3 # Make sure emma/ohlauer is not used as primary uplink
    ptp: true


  # 11s mesh 2ghz
  - vid: 20
    role: mesh
    name: mesh_11s_n2
    prefix: 10.31.115.41/32
    ipv6_subprefix: -10
    mesh_metric: 1024
    mesh_ap: zwingli-nord-nf-2ghz
    mesh_radio: 11g_standard
    mesh_iface: mesh
    mesh_metric_lqm:
      - default 0.4 # penalty on wild meshing
  - vid: 21
    role: mesh
    name: mesh_11s_o2
    prefix: 10.31.115.42/32
    ipv6_subprefix: -11
    mesh_metric: 1024
    mesh_ap: zwingli-ost-nf-2ghz
    mesh_radio: 11g_standard
    mesh_iface: mesh
    mesh_metric_lqm:
      - default 0.4 # penalty on wild meshing
#  - vid: 22
#    role: mesh
#    name: mesh_11s_s2
#    prefix: 10.31.115.43/32
#    ipv6_subprefix: -12
#    mesh_metric: 1024
#    mesh_ap: zwingli-sued-nf-2ghz
#    mesh_radio: 11g_standard
#    mesh_iface: mesh
#    mesh_metric_lqm:
#      - default 0.4 # penalty on wild meshing
  - vid: 23
    role: mesh
    name: mesh_11s_w2
    prefix: 10.31.115.44/32
    ipv6_subprefix: -13
    mesh_metric: 1024
    mesh_ap: zwingli-west-nf-2ghz
    mesh_radio: 11g_standard
    mesh_iface: mesh
    mesh_metric_lqm:
      - default 0.4 # penalty on wild meshing

  # 11s mesh 5ghz
  - vid: 24
    role: mesh
    name: mesh_11s_n5
    prefix: 10.31.115.45/32
    ipv6_subprefix: -14
    mesh_metric: 1024
    mesh_ap: zwingli-nord-nf-5ghz
    mesh_radio: 11a_standard
    mesh_iface: mesh
    mesh_metric_lqm:
      - default 0.4 # penalty on wild meshing
  - vid: 25
    role: mesh
    name: mesh_11s_o5
    prefix: 10.31.115.46/32
    ipv6_subprefix: -15
    mesh_metric: 1024
    mesh_ap: zwingli-ost-nf-5ghz
    mesh_radio: 11a_standard
    mesh_iface: mesh
    mesh_metric_lqm:
      - default 0.4 # penalty on wild meshing
#  - vid: 26
#    role: mesh
#    name: mesh_11s_s5
#    prefix: 10.31.115.47/32
#    ipv6_subprefix: -16
#    mesh_metric: 1024
#    mesh_ap: zwingli-sued-nf-5ghz
#    mesh_radio: 11a_standard
#    mesh_iface: mesh
#    mesh_metric_lqm:
#      - default 0.4 # penalty on wild meshing
  - vid: 27
    role: mesh
    name: mesh_11s_w5
    prefix: 10.31.115.48/32
    ipv6_subprefix: -17
    mesh_metric: 1024
    mesh_ap: zwingli-west-nf-5ghz
    mesh_radio: 11a_standard
    mesh_iface: mesh
    mesh_metric_lqm:
      - default 0.4 # penalty on wild meshing


location__channel_assignments_11a_standard__to_merge:
  zwingli-dome-1: 52-80
  zwingli-dome-2: 36-80
  zwingli-nno-nf-5ghz: 132-40-18 # EIRP 30dB - Antenna 14dB + Cable loss 2dB = 18dB

location__channel_assignments_11g_standard__to_merge:
  zwingli-dome-1: 1-20
  zwingli-dome-2: 13-20
