---
ipv6_prefix: 2001:bf7:760:2201::/56

uplink:
  ifname: lan3
  ipv4: 176.74.57.43/31
  ipv6: 2a04:d480:2001::1/127

mgmt:
  ifname: lan0.42
  ipv4: 10.31.83.49/29
  ipv6: 2001:bf7:760:2201::/64

# .49 gw
# .50 sw
# .51 mesh_hds
# .52 mesh_sama
# .53 mesh_segen
# .54 -

# Mesh Network: 10.31.83.56/30
mesh_links:
  - name: mesh_hds
    ifname: lan0.10
    ipv4: 10.31.83.56/32
    ipv6: 2001:bf7:760:2200::1/128 
    metric: 128
    ptp: true

  - name: mesh_sama
    ifname: lan0.11
    ipv4: 10.31.83.57/32
    ipv6: 2001:bf7:760:2200::2/128 
    metric: 128
    ptp: true

  - name: mesh_segen
    ifname: lan0.12
    ipv4: 10.31.83.58/32
    ipv6: 2001:bf7:760:2200::3/128
    metric: 128
    ptp: true

# Downlink IPv4 is in net announced by emma.

sgw: "1000000 1000000"
# OLSR Announce SmartGateway

tunnel_metric: 1024
# Tunnel metric 1024 as most internet uplinks will hardly reach 40MBit/s
# 2001:bf7:760:2200::/56 is the base prefix

wireguard_base_prefix: 2001:bf7:760:2202::/64
gre_base_prefix: 2001:bf7:760:2201::/64

 
# gre tunnel alias will be used as remote ifname. Must not exceed 9 chars
gre_tunnel_alias: saarbrue
