---
ipv6_prefix: "2001:bf7:860::/56"

networks:
  - vid: 42
    role: mgmt
    prefix: 10.31.81.0/27
    gateway: 1
    dns: 1
    ipv6_subprefix: 1
    assignments:
      sama-core: 1
      sama-poe-1: 2
      sama-poe-2: 3
# 6-15 (Local APs)
      sama-nord-nf-5ghz: 10
      sama-ost-nf-5ghz: 11
      sama-sued-nf-5ghz: 12
      sama-west-nf-5ghz: 13
# 16-31 (BBB)
      sama-nord-5ghz: 20
      sama-ost-5ghz: 21
      sama-sued-5ghz: 22
      sama-west-5ghz: 23

  - vid: 40
    role: dhcp
    prefix: 10.31.80.128/25
    ipv6_subprefix: 0
    inbound_filtering: true
    enforce_client_isolation: true
    assignments:
      sama-core: 1


# 10.31.79.176/28 Mesh Prefix (16)
  - vid: 10
    role: mesh
    name: mesh_nord
    prefix: 10.31.79.176/32
    ipv6_subprefix: -1
    assignments:
      sama-core: 0
  - vid: 11
    role: mesh
    name: mesh_ost
    prefix: 10.31.79.177/32
    ipv6_subprefix: -2
    assignments:
      sama-core: 0
  - vid: 12
    role: mesh
    name: mesh_sued
    prefix: 10.31.79.178/32
    ipv6_subprefix: -3
    assignments:
      sama-core: 0
  - vid: 13
    role: mesh
    name: mesh_west
    prefix: 10.31.79.179/32
    ipv6_subprefix: -4
    assignments:
      sama-core: 0

location__channel_assignments_11a_standard__to_merge:
  sama-nord-nf-5ghz: 44-40
  sama-ost-nf-5ghz: 36-40
  sama-sued-nf-5ghz: 44-40
  sama-west-nf-5ghz: 36-40

# Back to Back channel is reused
# - Hopefully rf-Shield performs :)
