---
ipv6_prefix: "2001:bf7:860:900::/56"

# Disable noping as we use dhcp and static assignments
# both in w10-host network
dhcp_no_ping: false


# Mesh: 10.230.210.104/29
networks:
  - vid: 10
    role: mesh
    name: mesh_sama
    prefix: 10.230.210.104/32
    ipv6_subprefix: -1
    ptp: true

  - vid: 11
    role: mesh
    name: mesh_zwingli
    prefix: 10.230.210.105/32
    ipv6_subprefix: -2
    ptp: true

  - vid: 20
    role: mesh
    name: mesh_east_2g
    prefix: 10.230.210.106/32
    ipv6_subprefix: -3
    mesh_metric: 2048
    mesh_ap: wilgu10-east-nf-2ghz
    mesh_radio: 11g_standard
    mesh_iface: mesh

  - vid: 42
    role: mgmt
    prefix: 10.36.190.176/28
    gateway: 1
    dns: 1
    ipv6_subprefix: 1
    assignments:
      wilgu10-core: 1
      wilgu10-int: 2
      wilgu10-east-nf: 3
      wilgu10-west-nf: 4
      wilgu10-zwingli: 5 # rocket 5 ac lite
      wilgu10-sama: 6 #  af60-lr
      wilgu10-east-nf-2ghz: 7

  - vid: 40
    role: dhcp
    prefix: 10.36.164.64/27
    ipv6_subprefix: 0
    inbound_filtering: true
    enforce_client_isolation: true
    assignments:
      wilgu10-core: 1

  - vid: 41
    name: prdhcp
    role: dhcp
    prefix: 10.31.154.96/28
    ipv6_subprefix: 10
    inbound_filtering: true
    assignments:
      wilgu10-core: 1
      wilgu10-printer: 2
    untagged: true

  - vid: 50
    role: dhcp
    name: w10host
    prefix: 10.31.124.32/28
    ipv6_subprefix: 50
    assignments:
      wilgu10-core: 1
      wilgu10-gf: 2
      uisp: 3

location__channel_assignments_11a_standard__to_merge:
  wilgu10-core: 36-80
  wilgu10-int: 52-20
  wilgu10-east-nf: 36-20
  wilgu10-west-nf: 36-20

location__channel_assignments_11g_standard__to_merge:
  wilgu10-core: 6-20-3
  wilgu10-int: 1-20-3
  wilgu10-east-nf-2ghz: 13-20
