---
ipv6_prefix: "2001:bf7:830:8900::/56"

# Borussia got following prefixes:
# Router: 10.31.96.0/27
# --MGMT: 10.31.96.0/28
# --MESH: 10.31.96.16/28
# --DHCP: 10.31.142.128/25

networks:
  - vid: 40
    role: dhcp
    inbound_filtering: true
    enforce_client_isolation: true
    prefix: 10.31.142.128/25
    ipv6_subprefix: 0
    assignments:
      borussia-core: 1

  - vid: 41
    name: prdhcp
    role: ext
    untagged: true

  - vid: 42
    role: mgmt
    prefix: 10.31.96.0/28
    gateway: 1
    dns: 1
    ipv6_subprefix: 1
    assignments:
      borussia-core: 1
      borussia-ap1: 14
      borussia-ap2: 13
      borussia-ap3: 12
