---
- name: Include tasks for merging variables
  include_tasks:
    file: merge_vars.yml
    apply:
      tags: always
  tags: always

- name: Include tasks for conditional packages
  include_tasks:
    file: conditional_packages.yml
    apply:
      tags: always
  tags: always

- name: Prepare some variables (1)
  set_fact:
    basedir: /tmp/ansible-openwrt
  tags: always

- name: Prepare some variables
  set_fact:
    config_path: "{{ basedir }}/configs/{{ inventory_hostname }}"
    imagebuilder_dir: "{{ basedir }}/imagebuilders/"
    imagebuild_dir: "{{ basedir }}/tmp/imagebuild/{{ inventory_hostname }}"
    image_dir: "{{ basedir }}/images/"
    wikiupdater_dir: "{{ basedir }}/wikiupdater/"
  tags: always

- name: Create directory
  file:
    path: "{{ config_path }}"
    state: directory
    mode: "755"
  tags: always

- name: Include render_etc.yml
  include_tasks:
    file: render_etc.yml
    apply:
      tags: always
  tags: always

- name: Include add_symlinks.yml
  include_tasks:
    file: add_symlinks.yml
    apply:
      tags: always
  tags: always

- name: Add poemgr config if poemgr target
  template:
    src: "{{ role_path }}/templates/common/config/poemgr.j2"
    dest: "{{ config_path }}/etc/config/poemgr"
    mode: "644"
  when:
    - poemgr_ports is defined
  tags: always

- name: "Make sure /lib/firmware is present"
  file:
    dest: "{{ config_path }}/lib/firmware/ath10k"
    state: directory
    recurse: true
  when: ath10k_ct_fwcfg is defined
  tags: always

- name: "Configure ath10k-ct driver"
  copy:
    dest: "{{ config_path }}/lib/firmware/ath10k/fwcfg-{{ item.id }}.txt"
    content: "{{ item.config }}"
    mode: "644"
  loop: "{{ ath10k_ct_fwcfg | default([]) }}"
  tags: always

- name: Include fix_permissions.yml
  include_tasks:
    file: fix_permissions.yml
    apply:
      tags: always
  tags: always

- name: Include image generation
  include_tasks:
    file: imagebuilder.yml
    apply:
      tags: always
  tags:
    - never
    - image
    - flash

- name: Include image flash
  include_tasks:
    file: flash.yml
    apply:
      tags: always
  tags:
    - never
    - flash
  when: ipv6_prefix is defined

- name: Include wikiupdater
  include_tasks:
    file: wikiupdater.yml
    apply:
      tags: wiki
  tags: wiki
  when: role == "corerouter"

- name: Wikiupdaterinfo
  ansible.builtin.debug:
    msg:
      - Role from your current device is {{ role }}. Wikiupdater needs to be run with the Corerouter.
      - You might need to change your limit to include the core-router if you dont get the desired output.
  tags: wiki
  when: role != "corerouter"
