---
- name: Include tasks for merging variables
  include_tasks:
    file: merge_vars.yml
    apply:
      tags: always
  tags: always

- name: Include tasks for conditional packages
  include_tasks:
    file: conditional_packages.yml
    apply:
      tags: always
  tags: always

- name: Prepare some variables (1)
  set_fact:
    basedir: "{{ playbook_dir }}/tmp"
  tags: always

- name: Prepare some variables
  set_fact:
    configs_dir: "{{ basedir }}/configs/{{ inventory_hostname }}"
    dl_dir: "{{ basedir }}/dl/"
    build_dir: "{{ basedir }}/build/{{ inventory_hostname }}"
    images_dir: "{{ basedir }}/images/"
    wikiupdater_dir: "{{ basedir }}/wikiupdater/"
  tags: always

- name: Create directory
  file:
    path: "{{ configs_dir }}"
    state: directory
    mode: "755"
  tags:
    - always
    - config

- name: Include render_etc.yml
  include_tasks:
    file: render_etc.yml
    apply:
      tags: always
  tags:
    - always
    - config

- name: Include add_symlinks.yml
  include_tasks:
    file: add_symlinks.yml
    apply:
      tags: always
  tags:
    - always
    - config

- name: Add poemgr config if poemgr target
  template:
    src: "{{ role_path }}/templates/common/config/poemgr.j2"
    dest: "{{ configs_dir }}/etc/config/poemgr"
    mode: "644"
  when:
    - poemgr_ports is defined
  tags:
    - always
    - config

- name: "Make sure /lib/firmware is present"
  file:
    dest: "{{ configs_dir }}/lib/firmware/ath10k"
    state: directory
    recurse: true
  when: ath10k_ct_fwcfg is defined
  tags:
    - always
    - config

- name: "Configure ath10k-ct driver"
  copy:
    dest: "{{ configs_dir }}/lib/firmware/ath10k/fwcfg-{{ item.id }}.txt"
    content: "{{ item.config }}"
    mode: "644"
  loop: "{{ ath10k_ct_fwcfg | default([]) }}"
  tags:
    - always
    - config

- name: Include fix_permissions.yml
  include_tasks:
    file: fix_permissions.yml
    apply:
      tags: always
  tags:
    - always
    - config

- name: Include image generation
  include_tasks:
    file: imagebuilder.yml
    apply:
      tags: always
  tags:
    - never
    - image
    - flash

- name: Include image flash
  include_tasks:
    file: flash.yml
    apply:
      tags: always
  tags:
    - never
    - flash
  when: ipv6_prefix is defined

- name: Include wikiupdater
  include_tasks:
    file: wikiupdater.yml
    apply:
      tags: wiki
  when: inventory_hostname in groups['role_corerouter']
  tags:
    - never
    - wiki
