---

snmp_devices:
  - hostname: philmel-rhnk
    address: 10.230.2.3
    snmp_profile: af60

  - hostname: philmel-ak36
    address: 10.230.2.4
    snmp_profile: airos_8

  - hostname: philmel-nord-5ghz
    address: 10.230.2.5
    snmp_profile: airos_8


# TODO BELOW
  - hostname: philmel-ost
    address: 10.230.2.165
    snmp_profile: airos_6

  - hostname: philmel-sued
    address: 10.230.2.169
    snmp_profile: airos_6

  - hostname: philmel-west
    address: 10.230.2.173
    snmp_profile: airos_6

  - hostname: philmel-autobahn
    address: 10.230.2.185
    snmp_profile: airos_8

  - hostname: philmel-vaterhaus
    address: 10.230.2.189
    snmp_profile: airos_8
