---
ipv6_prefix: "2001:bf7:830:8800::/56"

# Rio-Reiser got following prefixes:
# Router: 10.31.139.0/27
# --MGMT: 10.31.139.0/28
# --MESH: 10.31.139.16/28
# --DHCP: 10.31.138.128/25

networks:
  - vid: 10
    role: mesh
    name: mesh_simeon
    prefix: 10.31.139.16/32
    ipv6_subprefix: -1

  - vid: 40
    role: dhcp
    inbound_filtering: true
    enforce_client_isolation: true
    prefix: 10.31.138.128/25
    ipv6_subprefix: 0
    assignments:
      kub-core: 1

  - vid: 42
    role: mgmt
    prefix: 10.31.139.0/28
    gateway: 1
    dns: 1
    ipv6_subprefix: 1
    assignments:
      kub-core: 1
      kub-simeon: 2
      kub-ap1: 14

# Special vlan config:
# - kub-ap1 vlan 40: 0t 1t 2 3 4
