---


snmp_devices:
  - hostname: hds-saarbruecker
    address: 10.36.166.126
    snmp_profile: mikrotik_60g

  - hostname: saarbruecker-hds
    address: 10.31.83.51
    snmp_profile: mikrotik_60g

  - hostname: hds-sama
    address: 10.36.166.130
    snmp_profile: airos_8

  - hostname: hds-simeon
    address: 10.36.166.134
    snmp_profile: airos_8

  - hostname: hds-nord
    address: 10.36.166.122
    snmp_profile: airos_8
