---
ipv6_prefix: "2001:bf7:831::/56"

# Emma got 10.31.11.0/24 as prefix
networks:
  - vid: 84
    role: mgmt
    prefix: 10.31.11.1/27
    gateway: 1
    dns: 1
    ipv6_subprefix: 1
    assignments:
      emma-core: 1
      emma-switch-no: 2
      emma-switch-so: 3
      emma-switch-sw: 4
      emma-switch-nw: 5
#     emma-nno-2ghz: 10
      emma-ono-2ghz: 11
      emma-oso-2ghz: 12
      emma-sso-2ghz: 13
#     emma-ssw-2ghz: 14
      emma-wsw-2ghz: 15
      emma-wnw-2ghz: 16
      emma-nnw-2ghz: 17
      # airos
      emma-ssw-uplink: 18
      emma-nnw-5ghz: 19
      emma-nno-5ghz: 20
      emma-ono-5ghz: 21
      emma-wsw-5ghz: 22
      emma-wnw-5ghz: 23
      emma-oso-5ghz: 24
      emma-sso-5ghz: 25

  - vid: 40
    role: dhcp
    prefix: 10.31.11.128/25
    ipv6_subprefix: 0
    inbound_filtering: true
    enforce_client_isolation: true
    assignments:
      emma-core: 1

  - vid: 21
    role: mesh
    name: mesh_nno
    prefix: 10.31.11.65/30
    ipv6_subprefix: -1

  - vid: 22
    role: mesh
    name: mesh_ono
    prefix: 10.31.11.69/30
    ipv6_subprefix: -2

  - vid: 31
    role: mesh
    name: mesh_oso
    prefix: 10.31.11.73/30
    ipv6_subprefix: -3

  - vid: 32
    role: mesh
    name: mesh_sso
    prefix: 10.31.11.77/30
    ipv6_subprefix: -4

    # uplink via Airfiber 
  - vid: 41
    role: mesh
    name: mesh_ssw
    prefix: 10.31.11.97/29
    ipv6_subprefix: -5
    mesh_metric: 256
    ptp: true

  - vid: 42
    role: mesh
    name: mesh_wsw
    prefix: 10.31.11.85/30
    ipv6_subprefix: -6
  
  - vid: 51
    role: mesh
    name: mesh_wnw
    prefix: 10.31.11.89/30
    ipv6_subprefix: -7

  # Segen
  - vid: 52
    role: mesh
    name: mesh_nnw
    prefix: 10.31.11.93/30
    ipv6_subprefix: -8
