---
role_uplink_gw__packages__to_merge:
  - -wpad-openssl
  - collectd-mod-conntrack
  - collectd-mod-olsrd
  - collectd-mod-snmp
  - collectd-mod-snmp6
  - olsrd
  - olsrd-mod-arprefresh
  - olsrd-mod-dyn-gw
  - olsrd-mod-jsoninfo
  - olsrd-mod-nameservice
  - olsrd-mod-txtinfo
  - olsrd-utils
  - kmod-ipip
  - luci-app-olsr
  - luci-app-olsr-services
  - luci-mod-falter
  - falter-common
  - luci-app-falter-owm
  - luci-app-falter-owm-ant
  - luci-app-falter-owm-cmd
  - luci-app-falter-owm-gui
  - iptables-mod-ipopt
  - kmod-ipt-ipopt
  - bird2-babelpatch
  - bird2c
  - bgpdisco
  - bgpdisco-plugin-nameservice
  - ip-full
  - gre
  - wireguard-tools
  - kmod-wireguard
  - wg-installer-server
  - wg-installer-server-hotplug-olsrd
  - conntrackd
  - samplicator

role_uplink_gw__disabled_services__to_merge:
  - "odhcpd"
