---
# Overall we allocated: 10.31.125.0/24
# Still unused:
# - 10.31.125.64/26

ipv6_prefix: "2001:bf7:810:1000::/56"

networks:
  # 10.31.125.32/27 for meshing
  - vid: 10
    role: mesh
    name: mesh_rhxb
    prefix: 10.31.125.32/32
    ipv6_subprefix: -1

  - vid: 11
    role: mesh
    name: mesh_2ghz_s
    prefix: 10.31.125.33/32
    ipv6_subprefix: -2
    mesh_ap: manstein10-m2-s
    mesh_radio: 11g_standard
    mesh_iface: mesh

  - vid: 12
    role: mesh
    name: mesh_2ghz_w
    prefix: 10.31.125.34/32
    ipv6_subprefix: -3
    mesh_ap: manstein10-m2-w
    mesh_radio: 11g_standard
    mesh_iface: mesh

  # 10.31.125.32/25 for dhcp
  - vid: 40
    role: dhcp
    inbound_filtering: true
    enforce_client_isolation: true
    prefix: 10.31.125.128/25
    ipv6_subprefix: 0
    assignments:
      manstein10-core: 1

  # 10.31.125.0/27 for mgmt
  - vid: 42
    role: mgmt
    prefix: 10.31.125.0/27
    gateway: 1
    dns: 1
    ipv6_subprefix: 1
    assignments:
      manstein10-core: 1
      manstein10-poe-switch-1: 2
      manstein10-poe-switch-2: 3
      # airos - bbb
      manstein10-rhxb: 4
      # airos - clients
      manstein10-m5-loco-s5: 5
      manstein10-m5-w5: 6
      # openwrt clients
      manstein10-m2-s: 7
      manstein10-m2-w: 8
