---
ipv6_prefix: "2001:bf7:830:9d00::/56"

# mesh: 10.31.109.64/30
networks:
  - vid: 10
    role: mesh
    name: mesh_sama
    prefix: 10.31.109.64/32
    ipv6_subprefix: -1
    ptp: true

  - vid: 11
    role: mesh
    name: mesh_zwingli
    prefix: 10.31.109.65/32
    ipv6_subprefix: -2
    ptp: true

  - vid: 42
    role: mgmt
    prefix: 10.31.119.128/27
    gateway: 1
    dns: 1
    ipv6_subprefix: 1
    assignments:
      rigaer78-core: 1
      rigaer78-poe: 2 # reserved
      rigaer78-sama: 3
      rigaer78-zwingli: 4
      # aps
      rigaer78-east-5ghz: 30
      rigaer78-east-2ghz: 29
      rigaer78-west-5ghz: 28
      rigaer78-west-2ghz: 27
      rigaer78-eap225: 26

  - vid: 40
    role: dhcp
    prefix: 10.31.122.0/24
    ipv6_subprefix: 0
    inbound_filtering: true
    enforce_client_isolation: true
    assignments:
      rigaer78-core: 1

location__channel_assignments_11g_standard__to_merge:
  rigaer78-eap225: 11-20
  rigaer78-east-2ghz: 1-20-10
  rigaer78-west-2ghz: 6-20-10

location__channel_assignments_11a_standard__to_merge:
  rigaer78-eap225: 36-20
  rigaer78-east-5ghz: 40-20-10
  rigaer78-west-5ghz: 44-20-10
