---
role_corerouter__packages__to_merge:
  - babeld
  - luci-app-babeld
  - collectd-mod-dhcpleases
  - collectd-mod-olsrd
  - collectd-mod-exec
  - collectd-mod-conntrack
  - collectd-mod-snmp
  - olsrd
  - olsrd-mod-arprefresh
  - olsrd-mod-dyn-gw
  - olsrd-mod-jsoninfo
  - olsrd-mod-nameservice
  - olsrd-mod-txtinfo
  - olsrd-utils
  - luci-app-olsr
  - luci-app-olsr-services
  - luci-mod-falter
  - falter-common
  - luci-app-falter-owm
  - luci-app-falter-owm-ant
  - luci-app-falter-owm-cmd
  - luci-app-falter-owm-gui
  - iptables-mod-ipopt
  - kmod-ipt-ipopt
  - wg-installer-client
  - coreutils-timeout
  - coreutils-shuf
  - ip-full
