---
role_corerouter__packages__to_merge:
  - bgpdisco
  - bgpdisco-plugin-nameservice
  - olsrd
  - olsrd-mod-arprefresh
  - olsrd-mod-dyn-gw
  - olsrd-mod-jsoninfo
  - olsrd-mod-nameservice
  - olsrd-mod-txtinfo
  - olsrd-utils
  - luci-app-olsr
  - luci-app-olsr-services
  - luci-mod-falter
  - falter-common
  - luci-app-falter-owm
  - luci-app-falter-owm-ant
  - luci-app-falter-owm-cmd
  - luci-app-falter-owm-gui
  - iptables-mod-ipopt
  - kmod-ipt-ipopt

collectd__packages__to_merge:
  - collectd-mod-dhcpleases
  - collectd-mod-olsrd
  - collectd-mod-conntrack
  - collectd-mod-snmp

bird__packages__to_merge:
  - bird2-babelpatch
  - bird2c

tunnel__packages__to_merge:
  - tunspace
  - wireguard-tools

dfs__packages__to_merge:
  - airos-dfs-reset

util__packages__to_merge:
  - mosh-server
  - tmux

# There's no way to install only olsrd without olsrd6
all__disabled_services__to_merge:
  - "olsrd6"
