---
ipv6_prefix: '2001:bf7:830:8c00::/56'


# Mesh: 10.31.82.140/30
networks:
  - vid: 10
    role: mesh
    name: mesh_rhnk
    prefix: 10.31.82.140/32
    ipv6_subprefix: -2
    mesh_metric: 1024

  - vid: 11
    role: mesh
    name: mesh_vaterhaus
    prefix: 10.31.82.141/32
    ipv6_subprefix: -3
    mesh_metric: 1024

  - vid: 40
    role: dhcp
    inbound_filtering: true
    enforce_client_isolation: true
    prefix: 10.31.84.0/25
    ipv6_subprefix: 0
    assignments:
      kiehlufer-core: 1

  - vid: 42
    role: mgmt
    prefix: 10.31.82.208/28
    gateway: 1
    dns: 1
    ipv6_subprefix: 1
    assignments:
      kiehlufer-core: 1
      kiehlufer-switch: 2
      kiehlufer-rhnk: 3
      kiehlufer-vaterhaus: 4
      kiehlufer-nf-wbp1: 5
      kiehlufer-nf-wbp2: 6
      kiehlufer-nf-wbp3: 7
      kiehlufer-nf-wbp4: 8

location__channel_assignments_11a_standard__to_merge:
  kiehlufer-nf-wbp1: 36-20-15
  kiehlufer-nf-wbp2: 40-20-15
  kiehlufer-nf-wbp3: 44-20-15
  kiehlufer-nf-wbp4: 48-20-15

# Channel - Bandwidth - TX Power
