---

ipv6_prefix: '2001:bf7:830:8c00::/56'

# Mesh: 10.31.151.112/28
networks:
  # DEFAULT gateway - Wave Nano
  - vid: 10
    role: mesh
    name: mesh_rhnk
    prefix: 10.31.151.112/32
    ipv6_subprefix: -1
    mesh_metric: 1024
    ptp: true
  # gateway - PBE M5 300
  - vid: 11
    role: mesh
    name: mesh_philmel
    prefix: 10.31.151.113/32
    ipv6_subprefix: -2
    mesh_metric: 1024
    mesh_metric_lqm: ['default 0.3']
    ptp: true
  # gateway - Rocket 5AC lite
  - vid: 12
    role: mesh
    name: mesh_emma
    prefix: 10.31.151.114/32
    ipv6_subprefix: -3
    mesh_metric: 1024
    mesh_metric_lqm: ['default 0.2']
    ptp: true
  # mesh - mikrotik xtsq 5 ac
  - vid: 20
    role: mesh
    name: mesh_kiehl
    prefix: 10.31.151.115/32
    ipv6_subprefix: -4
    mesh_metric: 2048
    mesh_ap: kiehlufer-nf-wbp4
    mesh_radio: 11a_standard
    mesh_iface: mesh

  - vid: 40
    role: dhcp
    inbound_filtering: true
    enforce_client_isolation: true
    prefix: 10.31.84.0/25
    ipv6_subprefix: 0
    assignments:
      kiehlufer-core: 1

  - vid: 42
    role: mgmt
    prefix: 10.31.82.208/28
    gateway: 1
    dns: 1
    ipv6_subprefix: 1
    assignments:
      kiehlufer-core: 1
      kiehlufer-switch: 2
      kiehlufer-rhnk: 3
      kiehlufer-philmel: 4
      kiehlufer-emma: 5
      kiehlufer-nf-wbp1: 6
      kiehlufer-nf-wbp2: 7
      kiehlufer-nf-wbp3: 8
      kiehlufer-nf-wbp4: 9

  # - vid: 50
  #   untagged: true
  #   name: vpn_vdsl
  #   role: ext
  #   tunnel_wan_ip: 10.0.0.3/26
  #   tunnel_wan_gw: 10.0.0.1
  #   tunnel_connections: 2
  #   tunnel_timeout: 600
  #   tunnel_mesh_prefix_ipv4: 10.31.151.120/29

location__channel_assignments_11a_standard__to_merge:
  # Channel - Bandwidth - TX Power
  kiehlufer-nf-wbp1: 48-20
  kiehlufer-nf-wbp2: 40-20
  kiehlufer-nf-wbp3: 44-20
  kiehlufer-nf-wbp4: 36-20
