---
ipv6_prefix: "2001:bf7:830:9200::/56"

networks:
  - vid: 10
    role: mesh
    name: mesh_emma
    prefix: 10.31.98.188/32
    ipv6_subprefix: -1
    ptp: true

  - vid: 40
    role: dhcp
    inbound_filtering: true
    enforce_client_isolation: true
    prefix: 10.230.157.128/25
    ipv6_subprefix: 0
    assignments:
      rauchhaus-core: 1

  - vid: 41
    role: dhcp
    name: home
    no_corerouter_dns_record: true
    inbound_filtering: true
    enforce_client_isolation: false
    prefix: 10.31.169.128/25
    ipv6_subprefix: 1
    assignments:
      rauchhaus-core: 1

  - vid: 42
    role: mgmt
    prefix: 10.31.98.224/27
    gateway: 1
    dns: 1
    ipv6_subprefix: 1
    assignments:
      rauchhaus-core: 1
      rauchhaus-emma: 2
      rauchhaus-xdorf: 3
      rauchhaus-floor0north135: 10
      rauchhaus-floor0south136: 11
      rauchhaus-floor1north133: 12
      rauchhaus-floor1south134: 13
      rauchhaus-floor2north132: 14

location__channel_assignments_11a_standard__to_merge:
  rauchhaus-core: 36-20
  rauchhaus-floor0north135: 36-20
  rauchhaus-floor0south136: 48-20
  rauchhaus-floor1north133: 36-20
  rauchhaus-floor1south134: 48-20
  rauchhaus-floor2north132: 36-20

location__channel_assignments_11g_standard__to_merge:
  rauchhaus-core: 1-20
  rauchhaus-floor0north135: 11-20
  rauchhaus-floor0south136: 1-20
  rauchhaus-floor1north133: 6-20
  rauchhaus-floor1south134: 11-20
  rauchhaus-floor2north132: 1-20
