---
ipv6_prefix: "2001:bf7:820:1000::/56"

networks:
  - vid: 10
    role: mesh
    name: mesh_philmel
    prefix: 10.230.3.10/32
    ipv6_subprefix: -10
    mesh_metric: 128
    ptp: true

  - vid: 11
    role: mesh
    name: mesh_rhxb
    prefix: 10.230.3.11/32
    ipv6_subprefix: -11
    mesh_metric: 128
    ptp: true

  - vid: 13
    role: mesh
    name: mesh_vaterhaus
    prefix: 10.230.3.13/32
    ipv6_subprefix: -13

  - vid: 15
    role: mesh
    name: mesh_emma
    prefix: 10.230.3.15/32
    ipv6_subprefix: -15
    ptp: true
    mesh_metric: 512
    mesh_metric_lqm: ['default 0.7'] # prefer rhxb link

  - vid: 22
    role: mesh
    name: mesh_wsw
    prefix: 10.230.3.22/32
    ipv6_subprefix: -22

  - vid: 23
    role: mesh
    name: mesh_ono
    prefix: 10.230.3.23/32
    ipv6_subprefix: -23

  - vid: 24
    role: mesh
    name: mesh_oso
    prefix: 10.230.3.24/32
    ipv6_subprefix: -24

  - vid: 30
    role: mesh
    name: mesh_u1
    prefix: 10.36.91.30/32
    ipv6_subprefix: -30


  - vid: 40
    role: dhcp
    prefix: 10.230.3.64/26
    ipv6_subprefix: 0
    inbound_filtering: true
    enforce_client_isolation: true
    assignments:
      rhnk-core: 1

  - vid: 42
    role: mgmt
    prefix: 10.31.153.0/27 # 10.230.3.1/29 # 10.31.152.128/27
    gateway: 1
    dns: 1
    ipv6_subprefix: 1
    assignments:
      rhnk-core: 1
      rhnk-poe1: 2
      rhnk-poe2: 3
      rhnk-tplink-poe: 4 # default ip: 192.168.0.1

      # client access
      rhnk-platz: 9

      # 60 GHz P2P
      rhnk-philmel: 10
      rhnk-rhxb: 11
      rhnk-zwingli: 12
      rhnk-vaterhaus: 13

      # 5 GHz P2P
      rhnk-emma: 15
      rhnk-neukoelln: 16
      rhnk-fhain: 17

      # 5 GHz Sector
      rhnk-nnw: 20
      rhnk-wnw: 21 # down? old ip: 10.31.152.141
      rhnk-wsw: 22
      rhnk-ono: 23
      rhnk-oso: 24
      rhnk-ssw: 25
      rhnk-nno: 26






  # TODO: DISMANTLE!!!
  - vid: 12 # NO-PEERS
    role: mesh
    name: mesh_zwingli
    prefix: 10.230.3.12/32
    ipv6_subprefix: -12


  - vid: 16 # NO-PEERS
    role: mesh
    name: mesh_koelln
    prefix: 10.230.3.16/32
    ipv6_subprefix: -16

  - vid: 17 # NO-PEERS
    role: mesh
    name: mesh_fhain
    prefix: 10.230.3.17/32
    ipv6_subprefix: -17
    mesh_metric_lqm:
    - 10.31.7.149 0.2 # make sure emma is uplink and not f2a

  - vid: 20 # NO-PEERS
    role: mesh
    name: mesh_nnw
    prefix: 10.230.3.20/32
    ipv6_subprefix: -20

  - vid: 21 # NO-PEERS
    role: mesh
    name: mesh_wnw
    prefix: 10.230.3.21/32
    ipv6_subprefix: -21

  - vid: 25 # NO-PEERS
    role: mesh
    name: mesh_ssw
    prefix: 10.36.91.25/32
    ipv6_subprefix: -25

  - vid: 26 # NO-PEERS
    role: mesh
    name: mesh_nno
    prefix: 10.36.91.26/32
    ipv6_subprefix: -26
