---

snmp_devices:

  # 60 GHz
  - hostname: rhnk-philmel
    address: 10.31.153.10
    snmp_profile: af60

  - hostname: rhnk-rhxb
    address: 10.31.153.11
    snmp_profile: af60

  - hostname: rhnk-zwingli
    address: 10.31.153.12
    snmp_profile: af60

  - hostname: rhnk-vaterhaus
    address: 10.31.153.13
    snmp_profile: af60

  # 5 GHz P2P
  - hostname: rhnk-emma
    address: 10.31.153.15
    snmp_profile: airos_8

  - hostname: rhnk-neukoelln
    address: 10.31.153.16
    snmp_profile: airos_8

  - hostname: rhnk-fhain
    address: 10.31.153.17
    snmp_profile: airos_6

  # 5 GHz Sector
  - hostname: rhnk-nnw
    address: 10.31.153.20
    snmp_profile: airos_8

  # down?
  #- hostname: rhnk-wnw
  #  address: 10.31.153.21
  #  snmp_profile: airos_6

  - hostname: rhnk-wsw
    address: 10.31.153.22
    snmp_profile: airos_6

  - hostname: rhnk-oso
    address: 10.31.153.23
    snmp_profile: airos_6

  - hostname: rhnk-oso
    address: 10.31.153.24
    snmp_profile: airos_8

  - hostname: rhnk-ssw
    address: 10.31.153.25
    snmp_profile: airos_8

