---

snmp_devices:
  - hostname: schreiner-f2a
    address: 10.31.97.98
    snmp_profile: airos_6

  - hostname: schreiner-sama
    address: 10.31.97.99
    snmp_profile: airos_6

  - hostname: schreiner-client-1
    address: 10.31.97.101
    snmp_profile: airos_6

  - hostname: schreiner-client-2
    address: 10.31.97.102
    snmp_profile: airos_6
