---

airos_dfs_reset:
  - name: "segen-f2a"
    target: "10.31.6.11"
    username: "ubnt"
    password: "file:/root/pwd"
    daytime_limit: "2-7"
  - name: "segen-mabb"
    target: "10.31.6.12"
    username: "ubnt"
    password: "file:/root/pwd"
    daytime_limit: "2-7"
  - name: "segen-bht"
    target: "10.31.6.14"
    username: "ubnt"
    password: "file:/root/pwd"
    daytime_limit: "2-7"
  - name: "segen-k12"
    target: "10.31.6.15"
    username: "ubnt"
    password: "file:/root/pwd"
    daytime_limit: "2-7"
