---
ipv6_prefix: "2001:bf7:830:b100::/56"

networks:

  - vid: 42
    role: mgmt
    prefix: 10.31.15.196/32
    gateway: 1
    dns: 1
    ipv6_subprefix: 1
    assignments:
      suedblock-core: 1

  - vid: 40
    role: dhcp
    prefix: 10.31.172.128/25
    ipv6_subprefix: 0
    inbound_filtering: true
    enforce_client_isolation: true
    assignments:
      suedblock-core: 1

  - vid: 23
    role: ext
    name: uplink
    tunnel_wan_ip: 192.168.178.21/24
    tunnel_wan_gw: 192.168.178.1
    tunnel_timeout: 600
    tunnel_connections: 2
    tunnel_mesh_prefix_ipv4: 10.31.172.32/28
