---
ipv6_prefix: "2001:bf7:830:8200::/56"

networks:
# 10.31.74.220/30 is reserved for meshing
  - vid: 10
    role: mesh
    name: mesh_sama
    prefix: 10.31.74.220/32
    ipv6_subprefix: -1
    ptp: true

  - vid: 11
    role: mesh
    name: mesh_zwingli
    prefix: 10.31.74.221/32
    ipv6_subprefix: -2
    ptp: true

  - vid: 40
    role: dhcp
    inbound_filtering: true
    enforce_client_isolation: true
    prefix: 10.31.120.0/24
    ipv6_subprefix: 0
    assignments:
      dorfplatz-core: 1

  - vid: 42
    role: mgmt
    prefix: 10.31.75.32/28
    gateway: 1
    dns: 1
    ipv6_subprefix: 1
    assignments:
      dorfplatz-core: 1
      dorfplatz-poe-switch: 2
      dorfplatz-sama: 3
      dorfplatz-zwingli: 4
      dorfplatz-ap1: 14
      dorfplatz-ap2: 13
      dorfplatz-ap3: 12

location__channel_assignments_11a_standard__to_merge:
  dorfplatz-ap1: 36-20-15
  dorfplatz-ap2: 40-20-15
