---

ipv6_prefix: '2001:bf7:830:8d00::/56'

# K9 Prefixes:
# 10.31.9.0/24

# - 10.31.9.0/25 - DHCP
# - 10.31.9.208/28 - MGMT
# - 10.31.9.224/28 - BBB-Mesh
# - 10.31.9.240/28 - Internal Mesh


# 10.31.99.0/24 / can be proably dismantled



networks:
  - vid: 10
    role: mesh
    name: mesh_sama
    prefix: 10.31.9.224/32
    ipv6_subprefix: -1
    mesh_metric: 512

  - vid: 11
    role: mesh
    name: mesh_zwingli
    prefix: 10.31.9.225/32
    ipv6_subprefix: -2
    mesh_metric: 1024

  - vid: 12
    role: mesh
    name: mesh_wilgu10
    prefix: 10.31.9.226/32
    ipv6_subprefix: -3
    mesh_metric: 512

  - vid: 20
    role: mesh
    name: mesh_k9int
    prefix: 10.31.9.240/28
    ipv6_subprefix: -3
    mesh_metric: 64
    assignments:
      k9-core: 1

  - vid: 40
    role: dhcp
    inbound_filtering: true
    enforce_client_isolation: true
    prefix: 10.31.9.0/25
    ipv6_subprefix: 0
    assignments:
      k9-core: 1

  - vid: 42
    role: mgmt
    prefix: 10.31.9.208/28
    gateway: 1
    dns: 1
    ipv6_subprefix: 1
    assignments:
      k9-core: 1
      k9-switch: 2
      k9-sama: 3
      k9-zwingli: 4
      k9-wilgu10: 5
