---
ipv6_prefix: '2001:bf7:840:c00::/56'

# mesh: 10.31.166.192/28
# mgmt: 10.31.166.208/28
# dhcp: 10.31.167.0/26
networks:

  - vid: 20
    role: mesh
    name: mesh_core
    prefix: '10.31.166.193/32'
    ipv6_subprefix: -1

  - vid: 21
    role: mesh
    name: mesh_ap1
    prefix: '10.31.166.194/32'
    ipv6_subprefix: -2
    mesh_metric: 1024
    mesh_ap: kts13-ap1
    mesh_radio: 11a_standard
    mesh_iface: mesh

  - vid: 40
    role: dhcp
    prefix: '10.31.167.0/26'
    ipv6_subprefix: 0
    inbound_filtering: true
    enforce_client_isolation: true
    assignments:
      kts13-core: 1

  - vid: 42
    role: mgmt
    prefix: '10.31.166.208/28'
    gateway: 1
    dns: 1
    ipv6_subprefix: 1
    assignments:
      kts13-core: 1
      kts13-ap1: 2

  - vid: 50
    role: ext
    name: otwo
    untagged: true
    tunnel_wan_ip: '192.168.254.2/24'
    tunnel_wan_gw: '192.168.254.1'
    tunnel_connections: 2
    tunnel_timeout: 600
    tunnel_mesh_prefix_ipv4: '10.31.166.192/28'

location__channel_assignments_11a_standard__to_merge:
  kts13-ap1: 36-40-7 # 7 dBm + 16 dBi gain = 23 dBm
