---
ipv6_prefix: "2001:bf7:830:8e00::/56"

networks:
  - vid: 10
    role: mesh
    name: mesh_sama
    prefix: 10.31.79.67/32
    ipv6_subprefix: -1
    ptp: true

  - vid: 11
    role: mesh
    name: mesh_rhnk
    prefix: 10.31.54.227/32
    ipv6_subprefix: -2
    ptp: true

  - vid: 42
    role: mgmt
    prefix: 10.31.81.80/28
    gateway: 1
    dns: 1
    ipv6_subprefix: 1
    assignments:
      rigaer83-core: 1
      rigaer83-poe: 2
      rigaer83-sama: 3
      rigaer83-zwingli: 4

      # riagaer83
      rigaer83-front-5: 9
      rigaer83-front-2: 8
      rigaer83-back-5: 7
      rigaer83-back-2: 6

  - vid: 40
    role: dhcp
    prefix: 10.31.118.0/24
    ipv6_subprefix: 0
    inbound_filtering: true
    enforce_client_isolation: true
    assignments:
      rigaer83-core: 1

location__channel_assignments_11a_standard__to_merge:
  rigaer83-core: 52-80
  rigaer83-front-5: 36-20-15
  rigaer83-back-5:  40-20-15

location__channel_assignments_11g_standard__to_merge:
  rigaer83-core: 6-20
  rigaer83-front-2: 1-20
  rigaer83-back-2: 13-20
