---

location: kfetisch
role: corerouter
model: "tplink_archer-c7-v5"                                                                                                                                                                                     

wireless_profile: freifunk_default
