---
ipv6_prefix: "2001:bf7:750:4a00::/56"
# mesh: 10.31.147.224/29
# mgmt: 10.31.146.128/26
# dhcp: 10.31.147.0/25

networks:
  - vid: 20
    role: mesh
    name: mesh_hb-ap-c1
    prefix: 10.31.147.225/32
    ipv6_subprefix: -1
    mesh_ap: habersaath-ap-c1
    mesh_radio: 11a_standard
    mesh_iface: mesh
    mesh_metric_lqm:
      - default 0.2       # Penalty so local uplink is preferred

  - vid: 42
    role: mgmt
    prefix: 10.31.146.128/26
    gateway: 1
    dns: 1
    ipv6_subprefix: 1
    assignments:
      habersaath-core: 1
      habersaath-sw-a: 2
      habersaath-sw-b: 3
      habersaath-sw-c: 4
      habersaath-ap-a1: 12
      habersaath-ap-a2: 13
      habersaath-ap-a3: 14
      habersaath-ap-a4: 15
      habersaath-ap-a5: 16
      habersaath-ap-a6: 17
      habersaath-ap-b1: 18
      habersaath-ap-b2: 19
      habersaath-ap-b3: 20
      habersaath-ap-b4: 21
      habersaath-ap-b5: 22
      habersaath-ap-b6: 23
      habersaath-ap-c1: 24
      habersaath-ap-c2: 25
      habersaath-ap-c3: 26
      habersaath-ap-c4: 27
      habersaath-ap-c5: 28
      habersaath-ap-c6: 29

  - vid: 40
    role: dhcp
    prefix: 10.31.147.0/25
    ipv6_subprefix: 0
    inbound_filtering: true
    enforce_client_isolation: true
    assignments:
      habersaath-core: 1

  - vid: 50
    untagged: true
    name: vpn_lte
    role: ext
    tunnel_wan_ip: 192.168.2.2/24
    tunnel_wan_gw: 192.168.2.1
    tunnel_connections: 1
    tunnel_timeout: 600
    tunnel_mesh_prefix_ipv4: 10.31.147.224/29

location__channel_assignments_11a_standard__to_merge:
  habersaath-ap-a1: 36-20
  habersaath-ap-a2: 40-20
  habersaath-ap-a3: 44-20
  habersaath-ap-a4: 48-20
  habersaath-ap-a5: 36-20
  habersaath-ap-a6: 40-20
  habersaath-ap-b1: 44-20
  habersaath-ap-b2: 48-20
  habersaath-ap-b3: 36-20
  habersaath-ap-b4: 40-20
  habersaath-ap-b5: 44-20
  habersaath-ap-b6: 48-20
  habersaath-ap-c1: 36-20
  habersaath-ap-c2: 40-20
  habersaath-ap-c3: 44-20
  habersaath-ap-c4: 48-20
  habersaath-ap-c5: 36-20
  habersaath-ap-c6: 40-20

location__channel_assignments_11g_standard__to_merge:
  habersaath-ap-a1: 1-20
  habersaath-ap-a2: 5-20
  habersaath-ap-a3: 9-20
  habersaath-ap-a4: 13-20
  habersaath-ap-a5: 1-20
  habersaath-ap-a6: 5-20
  habersaath-ap-b1: 9-20
  habersaath-ap-b2: 13-20
  habersaath-ap-b3: 1-20
  habersaath-ap-b4: 5-20
  habersaath-ap-b5: 9-20
  habersaath-ap-b6: 13-20
  habersaath-ap-c1: 1-20
  habersaath-ap-c2: 5-20
  habersaath-ap-c3: 9-20
  habersaath-ap-c4: 13-20
  habersaath-ap-c5: 1-20
  habersaath-ap-c6: 5-20
