---

freifunk_global_prefix: 2001:bf7::/32
freifunk_wahlkreis_prefixes:
  - 2001:bf7:750::/44
  - 2001:bf7:760::/44
  - 2001:bf7:770::/44
  - 2001:bf7:780::/44
  - 2001:bf7:790::/44
  - 2001:bf7:800::/44
  - 2001:bf7:810::/44
  - 2001:bf7:820::/44
  - 2001:bf7:830::/44
  - 2001:bf7:840::/44
  - 2001:bf7:850::/44
  - 2001:bf7:860::/44

freifunk_wahlkreis_announcement_prefix: 44
# Change to 48 if you wnat to announce 48s

local_asn: 44194
peer_asn: 25291

role_uplink_gateway_sysctl__to_merge:
  net.netfilter.nf_conntrack_max: 524288

wireguard_port_start: 51820
wireguard_port_end: 52820
wireguard_wg_key: '/etc/wireguard/wg.key'
wireguard_wg_pub: '/etc/wireguard/wg.pub'
wireguard_wg_tmp_key: 1

gre_metric: 64



## FIREWALL SECTION


# For IPv6 there is a stateful firewall implemented. In order to
# archieve that using multiple active-active gateways, the
# flows (connection-tracking) have to get synced. As the
# outbound gateway (request, tracks state) could be different
# from the inbound gateway (looks for state to accept), the
# conntrack syncing would have to be faster than the actual
# request. For TCP We can cheat by accepting existing connections
# determined by the Flags, which dont belong to a (known) flow yet
# at a low rate.

conntrackd_port: 3780

# Rate Limit for packets with ACK flag set
untracked_flows_tcp_ack_rate: 5000
untracked_flows_tcp_ack_burst: 2500

# Rate Limit for packets with RST flag set
untracked_flows_tcp_rst_rate: 1000
untracked_flows_tcp_rst_burst: 500




# Inbound is filtered by default
inbound_allow:
  - name: 'k9-core SSH'
    dst: 2001:bf7:830:8d00::/128
    proto: tcp
    dst_port: 22
  - name: 'w10host'
    dst: 2001:bf7:860:932::/64
  - name: 'rigaer78-core SSH'
    dst: 2001:bf7:830:9d00::/128
    proto: tcp
    dst_port: 22
#  - name: Rule Description (mandatory)
#    dst: Destination IP (mandatory)
#    src: Source IP
#    proto: [tcp, udp, icmp.]
#    src_port:
#    dst_port: 22
